BrianChristyWedding/Models/Invitation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace BrianChristyWedding.Models
{
    public class Invitation
    {
        public const string ShortcodeKeyspace = "0123456789abcdefghijklmnopqrstuvwxyz";
        public const int ShortcodeLength = 4;

        public Invitation()
        {
            Address = new Address();
        }

        public int ID { get; set; }

        [Required]
        [Display(Name = "First name")]
        public string FirstName { get; set; }
        [Required]
        [Display(Name = "Last name")]
        public string LastName { get; set; }

        [Display(Name = "Custom address label name")]
        public string CustomAddressLabelName { get; set; }

        public string EffectiveName
        {
            get { return string.IsNullOrWhiteSpace(CustomAddressLabelName) ? FirstName + " " + LastName : CustomAddressLabelName; }
        }

        [Display(Name = "Guests allowed")]
        public int MaxAllowedGuests { get; set; }

        [Index(IsUnique = true)]
        [MaxLength(4)]
        [Display(Name = "Invitation code")]
        public string Shortcode { get; set; }

        public Address Address { get; set; }

        public virtual Rsvp Rsvp { get; set; }
    }
}

BrianChristyWedding/Areas/Admin/Controllers/InvitationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BrianChristyWedding.Models;
using System.Text;

namespace BrianChristyWedding.Areas.Admin.Controllers
{
    [BasicAuthentication("admin", "wedding1", BasicRealm = "BrianChristyWedding")]
    public class InvitationsController : Controller
    {
        private WeddingContext db = new WeddingContext();

        // GET: Admin/Invitations
        public ActionResult Index()
        {
            var invitations = db.Invitations.Include(i => i.Rsvp);
            return View(invitations.OrderBy(x => x.LastName).ToList());
        }

        // GET: Admin/Invitations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invitation invitation = db.Invitations.Find(id);
            if (invitation == null)
            {
                return HttpNotFound();
            }
            return View(invitation);
        }

        // GET: Admin/Invitations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Invitations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FirstName,LastName,CustomAddressLabelName,MaxAllowedGuests,Address")] Invitation invitation)
        {
            if (ModelState.IsValid)
            {
                db.Invitations.Add(invitation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(invitation);
        }

        // GET: Admin/Invitations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invitation invitation = db.Invitations.Find(id);
            if (invitation == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID = new SelectList(db.Rsvps, "InvitationID", "InvitationID", invitation.ID);
            return View(invitation);
        }

        // POST: Admin/Invitations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FirstName,LastName,CustomAddressLabelName,MaxAllowedGuests,Shortcode,Address")] Invitation invitation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(invitation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID = new SelectList(db.Rsvps, "InvitationID", "InvitationID", invitation.ID);
            return View(invitation);
        }

        // GET: Admin/Invitations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invitation invitation = db.Invitations.Find(id);
            if (invitation == null)
            {
                return HttpNotFound();
            }
            return View(invitation);
        }

        // POST: Admin/Invitations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Invitation invitation = db.Invitations.Find(id);
            db.Invitations.Remove(invitation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Export(string format = "csv")
        {
            if (format == "csv")
            {
                var invitations = db.Invitations;
                var csvResult = CsvGenerator.Generate(
                    invitations,
                    new CsvColumn<Invitation>("ID", x => x.ID),
                    new CsvColumn<Invitation>("FirstName", x => x.FirstName),
                    new CsvColumn<Invitation>("LastName", x => x.LastName),
                    new CsvColumn<Invitation>("CustomLabelName", x => x.CustomAddressLabelName),
                    new CsvColumn<Invitation>("Shortcode", x => x.Shortcode.ToUpper()),
                    new CsvColumn<Invitation>("MaxAllowedGuests", x => x.MaxAllowedGuests),
                    new CsvColumn<Invitation>("AddressLine1", x => x.Address.AddressLine1),
                    new CsvColumn<Invitation>("AddressLine2", x => x.Address.AddressLine2),
                    new CsvColumn<Invitation>("City", x => x.Address.City),
                    new CsvColumn<Invitation>("State", x => x.Address.State),
                    new CsvColumn<Invitation>("Zip", x => x.Address.Zip),
                    new CsvColumn<Invitation>("Shortcode_Link", x => "http://BrianAndChristyWedding.com/RSVP/" + x.Shortcode.ToUpper()),
                    new CsvColumn<Invitation>("EffectiveAddressName", x => string.IsNullOrWhiteSpace(x.CustomAddressLabelName) ? x.FirstName + " " + x.LastName : x.CustomAddressLabelName));
                
                return File(System.Text.Encoding.UTF8.GetBytes(csvResult), "text/csv", "Invitations.csv");
            }
            return HttpNotFound();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BrianChristyWedding/Areas/Admin/Controllers/RsvpsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BrianChristyWedding.Models;

namespace BrianChristyWedding.Areas.Admin.Controllers
{
    [BasicAuthentication("admin", "wedding1", BasicRealm = "BrianChristyWedding")]
    public class RsvpsController : Controller
    {
        private WeddingContext db = new WeddingContext();

        // GET: Admin/Rsvps
        public ActionResult Index()
        {
            var rsvps = db.Rsvps.Include(r => r.Invitation);
            return View(rsvps.OrderBy(x => x.Updated).ToList());
        }

        // GET: Admin/Rsvps/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rsvp rsvp = db.Rsvps.Find(id);
            if (rsvp == null)
            {
                return HttpNotFound();
            }
            return View(rsvp);
        }

        // GET: Admin/Rsvps/Create
        public ActionResult Create()
        {
            ViewBag.InvitationID = new SelectList(db.Invitations, "ID", "FullName");
            return View();
        }

        // POST: Admin/Rsvps/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "InvitationID,Created,Updated")] Rsvp rsvp)
        {
            if (ModelState.IsValid)
            {
                db.Rsvps.Add(rsvp);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.InvitationID = new SelectList(db.Invitations, "ID", "Name", rsvp.InvitationID);
            return View(rsvp);
        }

        // GET: Admin/Rsvps/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var rsvp = db.Rsvps.Find(id);
            if (rsvp == null)
            {
                return HttpNotFound();
            }
            ViewBag.InvitationID = new SelectList(db.Invitations, "ID", "Name", rsvp.InvitationID);
            return View(rsvp);
        }

        // POST: Admin/Rsvps/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "InvitationID,Created,Updated")] Rsvp rsvp)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rsvp).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.InvitationID = new SelectList(db.Invitations, "ID", "Name", rsvp.InvitationID);
            return View(rsvp);
        }

        // GET: Admin/Rsvps/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rsvp rsvp = db.Rsvps.Find(id);
            if (rsvp == null)
            {
                return HttpNotFound();
            }
            return View(rsvp);
        }

        // POST: Admin/Rsvps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Rsvp rsvp = db.Rsvps.Find(id);
            db.Rsvps.Remove(rsvp);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BrianChristyWedding/Controllers/RsvpController.cs
using BrianChristyWedding.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net.Mail;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace BrianChristyWedding.Controllers
{
    public class RsvpController : Controller
    {
        private readonly WeddingContext db = new WeddingContext();

        public ActionResult Index(string shortcode)
        {
            if (string.IsNullOrWhiteSpace(shortcode))
            {
                return View("Search");
            }
            else
            {
                //Retrieve RSVP info
                var invitation = db.Invitations.FirstOrDefault(x => x.Shortcode == shortcode);
                if (invitation == null)
                {
                    ModelState.AddModelError(
                        "Shortcode",
                        "Unable to find invitation code \"" + shortcode + ".\"  Please check your code and try again.");
                    return View("Search");
                }
                var rsvpVM = new RsvpEntryViewModel(invitation);
                return View("Welcome", rsvpVM);
            }
        }

        [HttpPost]
        public ActionResult Index([Bind(Include = "Shortcode")] RsvpSearchViewModel searchVM)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction("Index", new { shortcode = searchVM.Shortcode });
            }
            return View("Search");
        }

        [HttpPost]
        public ActionResult Submit([Bind(Include = "InvitationID,Attending,NumGuests,Guests,SongRequest")] RsvpEntryViewModel rsvpVM)
        {
            //Persist the Invitation information across requests
            var invitation = db.Invitations.Find(rsvpVM.InvitationID);
            if(invitation == null)
                return RedirectToAction("Index");
            rsvpVM.Invitation = invitation;

            if (ModelState.IsValid)
            {
                var rsvp = new Rsvp()
                {
                    InvitationID = rsvpVM.InvitationID,
                    Guests = rsvpVM.Guests,
                    Attending = rsvpVM.Attending.GetValueOrDefault(),
                    SongRequest = rsvpVM.SongRequest,
                    Invitation = rsvpVM.Invitation
                };
                AddOrUpdateRsvp(rsvp);
                db.SaveChanges();
                return View("Success", rsvpVM);
            }
            else
            {
                //Pad the number of guests, with empties
                while(rsvpVM.Guests.Count < invitation.MaxAllowedGuests)
                    rsvpVM.Guests.Add(new Guest());
            }
            return View("Welcome", rsvpVM);
        }

        private void AddOrUpdateRsvp(Rsvp rsvp)
        {
            var rsvpToUpdate = db.Rsvps.Find(rsvp.InvitationID);
            if (rsvpToUpdate != null)
            {
                rsvpToUpdate.Attending = rsvp.Attending;
                rsvpToUpdate.SongRequest = rsvp.SongRequest;
                db.Entry(rsvpToUpdate).State = System.Data.Entity.EntityState.Modified;
            }
            else
            {
                db.Rsvps.Add(rsvp);
            }
            AddOrUpdateGuests(rsvp.InvitationID, rsvp.Guests);
            SendEmailNotification(rsvp);

        }

        private void AddOrUpdateGuests(int invitationID, ICollection<Guest> guests)
        {
            var guestsToRemove = db.Guests.Where(x => x.RsvpID == invitationID);
            db.Guests.RemoveRange(guestsToRemove);

            if(guests == null)
                return;
            foreach (var guest in guests)
            {
                guest.RsvpID = invitationID;
                db.Guests.Add(guest);
            }
        }

        private void SendEmailNotification(Rsvp rsvp)
        {
            try
            {
                using (var smtp = new SmtpClient())
                {
                    var mail = new MailMessage();
                    mail.To.Add("bcpratt@live.com");
                    mail.To.Add("chrispy115@gmail.com");
                    mail.Subject = "Wedding RSVP Submitted or Updated";
                    mail.ReplyToList.Clear();
                    mail.ReplyToList.Add("no-reply@BrianAndChristyWedding.com");

                    var messageBody = new StringBuilder();
                    messageBody.AppendFormat("<p>An RSVP has been submitted (or updated) from <strong>{0}</strong>.</p>", rsvp.Invitation.EffectiveName);
                    messageBody.Append("<dl>");
                    messageBody.AppendFormat("<dt>Attending?:</dt><dd>{0}</dd>", rsvp.Attending ? "Yes" : "No");
                    if (rsvp.Attending)
                    {
                        messageBody.Append("<d><dt>Guests:</dt><dd><ul>");
                        foreach (var guest in rsvp.Guests)
                        {
                            messageBody.AppendFormat("<li>{0} ({1})</li>", guest.FirstName + " " + guest.LastName, guest.Age);
                        }
                        messageBody.Append("</ul></dd>");
                        messageBody.AppendFormat("<dt>Song request:</dt><dd>{0}</dd>", string.IsNullOrWhiteSpace(rsvp.SongRequest) ? "[None]" : rsvp.SongRequest);
                    }
                    messageBody.Append("</dl>");



                    mail.Body = messageBody.ToString();
                    mail.IsBodyHtml = true;

                    smtp.Send(mail);
                }
            }
            catch (Exception)
            {
                //Do nothing
            }
        }
    }
}

BrianChristyWedding/Areas/Admin/Views/Invitations/Create.cshtml
@model BrianChristyWedding.Models.Invitation

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Invitation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomAddressLabelName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomAddressLabelName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomAddressLabelName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxAllowedGuests, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxAllowedGuests, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxAllowedGuests, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BrianChristyWedding/Areas/Admin/Views/Invitations/Delete.cshtml
@model BrianChristyWedding.Models.Invitation

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Invitation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Rsvp.InvitationID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rsvp.InvitationID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomAddressLabelName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomAddressLabelName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxAllowedGuests)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxAllowedGuests)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Shortcode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Shortcode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BrianChristyWedding/Areas/Admin/Views/Invitations/Details.cshtml
@model BrianChristyWedding.Models.Invitation

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Invitation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Rsvp.InvitationID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rsvp.InvitationID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomAddressLabelName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomAddressLabelName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxAllowedGuests)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxAllowedGuests)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Shortcode)
        </dt>

        <dd class="shortcode">
            @Html.ActionLink(Model.Shortcode, "Index", "Rsvp", new { shortcode = Model.Shortcode, area = "" }, null)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BrianChristyWedding/Areas/Admin/Views/Invitations/Index.cshtml
@model IEnumerable<BrianChristyWedding.Models.Invitation>

@{
    ViewBag.Title = "Invitations";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>Shortcode</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Custom Label Name</th>
        <th>Address</th>
        <th>Number allowed</th>
        <th>RSVP</th>
        <th></th>
    </tr>
@{ 
    var totalInvitations = 0;
    var totalInvitedGuests = 0;
    var totalAttendingResponses = 0;
    var totalNotAttendingResponses = 0;
    var totalAttendingGuests = 0;
    var totalNotAttendingGuests = 0;

}
@foreach (var item in Model)
{
    <tr>
        <td class="shortcode">@(Html.Raw(item.Shortcode))</td>
        <td>@(Html.DisplayFor(modelItem => item.FirstName))</td>
        <td>@(Html.DisplayFor(modelItem => item.LastName))</td>
        <td>@(Html.DisplayFor(modelItem => item.CustomAddressLabelName))</td>
        <td>@(Html.DisplayFor(modelItem => item.Address))</td>
        <td>@(Html.DisplayFor(modelItem => item.MaxAllowedGuests))</td>
        <td>@(item.Rsvp == null ? Html.Raw("None") : Html.ActionLink(string.Format("{0} guests", item.Rsvp.Guests.Count), "Details", "Rsvps", new { id = item.Rsvp.InvitationID }, null))</td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
            @Html.ActionLink("Details", "Details", new { id = item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.ID })
        </td>
    </tr>
    totalInvitations++;
    totalInvitedGuests += item.MaxAllowedGuests;
    if (item.Rsvp != null)
    {
        if(item.Rsvp.Guests.Count > 0)
        {
            totalAttendingResponses++;
            totalAttendingGuests += item.Rsvp.Guests.Count;
            totalNotAttendingGuests += (item.MaxAllowedGuests - item.Rsvp.Guests.Count);
        }
        else
        {
            totalNotAttendingResponses++;
            totalNotAttendingGuests += item.MaxAllowedGuests;
        }
    }
}
</table>
@Html.ActionLink("Export to CSV", "Export")

<br />
<h3>Totals</h3>
<table class="table">
    <tr>
        <th></th>
        <th>Total</th>
        <th>Answered</th>
        <th>Unanswered</th>
        <th>Percent Responded</th>
    </tr>
    <tr>
        <th>Invitations</th>
        <td>@totalInvitations</td>
        <td>@(totalAttendingResponses + totalNotAttendingResponses)</td>
        <td>@(totalInvitations - totalAttendingResponses - totalNotAttendingResponses)</td>
        <td>
            @{ 
                var percent = (double)(totalAttendingResponses + totalNotAttendingResponses) / (double)totalInvitations * 100.0;
                @Html.Raw(percent.ToString("N0") + "%");
            }
        </td>
    </tr>
</table>
<br />
<table class="table">
    <tr>
        <th></th>
        <th>Attending</th>
        <th>Not Attending</th>
        <th>Remaining</th>
    </tr>
    <tr>
        <th>Responses</th>
        <td>@totalAttendingResponses</td>
        <td>@totalNotAttendingResponses</td>
        <td>@(totalInvitations - (totalAttendingResponses + totalNotAttendingResponses))</td>
    </tr>
</table>

<br />
<table class="table">
    <tr>
        <th></th>
        <th>Attending</th>
        <th>Not Attending</th>
        <th>Remaining</th>
        <th>Attending Percentage</th>
        <th>Estimated Turnout</th>
        <th>Worst-Case Scenario</th>
    </tr>
    <tr>
        <th>Guests</th>
        <td>@totalAttendingGuests</td>
        <td>@totalNotAttendingGuests</td>
        <td>
            @{
                var remainingGuests = totalInvitedGuests - (totalAttendingGuests + totalNotAttendingGuests);
            }
            @remainingGuests
        </td>
        <td>
            @{
                percent = (double)totalAttendingGuests / (double)(totalAttendingGuests + totalNotAttendingGuests) * 100.0;
                @Html.Raw(percent.ToString("N0") + "%");
            }
        </td>
        <td>@((int)(totalAttendingGuests + (remainingGuests * (percent / 100))))</td>
        <td>@(totalInvitedGuests - totalNotAttendingGuests)</td>
    </tr>
</table>